include:
  - backend/docker-compose.yml
  - frontend/docker-compose.yml

services:
  db:
    image: mongo
    restart: unless-stopped
    networks:
      - internal
    expose:
      - "27017"
    command: --port 27017

networks:
  internal:
    driver: bridge
